version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elib-app
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mongo
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
    networks:
      - elib-network

  mongo:
    image: mongo:latest
    container_name: elib-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-example}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE:-e_lib}
    volumes:
      - mongo-data:/data/db
    networks:
      - elib-network

networks:
  elib-network:
    driver: bridge

volumes:
  mongo-data:
